import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { supabase } from "@/lib/supabase";
import SiteHeader from "@/components/SiteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data: encounters } = await supabase.from("encounter").select("*");
  console.log(encounters);
  // const { data: monsters } = await supabase.from("monster").select("*");
  // console.log(encounters);
  return (
    <html lang="en">
      <body
        // className={`h-screen grid grid-cols-12 grid-rows-[48px_repeat(5,_1fr)] auto-rows-min ${inter.className}`}
        className={`flex flex-col h-screen ${inter.className}`}
      >
        <SiteHeader encounters={encounters} />
        <main className="h-full grid grid-cols-12 grid-rows-6">{children}</main>
      </body>
    </html>
  );
}
