import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { supabase } from "@/lib/supabase";
import SiteHeader from "@/components/SiteHeader";

import { collection, getDocs } from "firebase/firestore";
import { db } from "@/firebase/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getEncounters() {
  let encounters = [];
  const querySnapshot = await getDocs(collection(db, "encounters"));
  querySnapshot.forEach((doc) => {
    console.log(doc.id);
    encounters.push(doc.data());
  });
  return encounters;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const encounters = await getEncounters();
  // const { data: encounters } = await supabase.from("encounter").select("*");
  // console.log(encounters);

  return (
    <html lang="en">
      <body
        // className={`h-screen grid grid-cols-12 grid-rows-[48px_repeat(5,_1fr)] auto-rows-min ${inter.className}`}
        className={`flex flex-col h-screen ${inter.className}`}
      >
        <SiteHeader encounters={encounters} />
        <main className="h-full grid grid-cols-12 grid-rows-6">{children}</main>
      </body>
    </html>
  );
}
